package io.github.dsh.fastscript.bench;

import io.github.dsh.fastscript.ast.Ast;
import io.github.dsh.fastscript.core.EvalException;
import io.github.dsh.fastscript.core.Values;
import io.github.dsh.fastscript.runtime.Controls;
import io.github.dsh.fastscript.runtime.ExecContext;
import io.github.dsh.fastscript.runtime.Functions;
import io.github.dsh.fastscript.runtime.Host;
import io.github.dsh.fastscript.runtime.PlayerAccess;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * A straightforward tree-walking interpreter for the same AST the compiler consumes.
 *
 * <p>Its only purpose is the benchmark: measuring it against generated bytecode isolates the
 * benefit of compilation, because both run identical source and identical semantics. Classic
 * script engines such as Skript evaluate their parsed tree in essentially this way.</p>
 *
 * <p>Locals live in a hash map keyed by name, effects go through the same runtime dispatch as
 * compiled scripts, and control flow uses exceptions rather than jumps.</p>
 */
final class Interpreter {

    /** Per-call state: local bindings plus global bookkeeping. */
    final class InterpreterContext {

        private final Map<String, Object> locals = new HashMap<>();
        private final Object[] slots;
        private final ExecContext exec;

        InterpreterContext(Object[] slots, ExecContext exec) {
            this.slots = slots;
            this.exec = exec;
        }
    }

    private final Ast.Script script;
    private final Host host;

    Interpreter(Ast.Script script, Host host) {
        this.script = script;
        this.host = host;
    }

    InterpreterContext newContext() {
        // The interpreter keeps loop state in its own locals map, so it needs no frame array.
        Object[] slots = new Object[0];
        ExecContext exec = new ExecContext(host, null, null, new Object[0], "interpreter", "fn");
        return new InterpreterContext(slots, exec);
    }

    /** Invokes a script function by name. */
    Object call(String functionName, InterpreterContext context, Object... arguments) {
        Ast.FunctionDecl function = script.functions().stream()
                .filter(candidate -> candidate.name().equals(functionName))
                .findFirst()
                .orElseThrow(() -> new EvalException("unknown function '" + functionName + "'"));
        Map<String, Object> saved = new HashMap<>(context.locals);
        context.locals.clear();
        for (int i = 0; i < function.parameters().size(); i++) {
            context.locals.put(function.parameters().get(i), i < arguments.length ? arguments[i] : null);
        }
        try {
            try {
                execBlock(function.body(), context);
            } catch (Controls.ScriptReturn returned) {
                return returned.value();
            }
        } finally {
            context.locals.clear();
            context.locals.putAll(saved);
        }
        return null;
    }

    // ------------------------------------------------------------------ statements

    private void execBlock(List<Ast.Stmt> statements, InterpreterContext context) {
        for (Ast.Stmt statement : statements) {
            execStatement(statement, context);
        }
    }

    private void execStatement(Ast.Stmt statement, InterpreterContext context) {
        switch (statement) {
            case Ast.Assign assign -> assign(assign, context);
            case Ast.Condition condition -> {
                if (Values.toBool(eval(condition.test(), context))) {
                    execBlock(condition.then(), context);
                } else {
                    execBlock(condition.otherwise(), context);
                }
            }
            case Ast.While loop -> {
                while (Values.toBool(eval(loop.test(), context))) {
                    try {
                        execBlock(loop.body(), context);
                    } catch (Controls.LoopBreak ignored) {
                        break;
                    } catch (Controls.LoopContinue ignored) {
                        // Continue with the next iteration.
                    }
                }
            }
            case Ast.LoopTimes loop -> {
                double count = Values.toNumber(eval(loop.count(), context));
                for (int index = 0; index < count; index++) {
                    context.locals.put("loop-index", (double) index);
                    try {
                        execBlock(loop.body(), context);
                    } catch (Controls.LoopBreak ignored) {
                        break;
                    } catch (Controls.LoopContinue ignored) {
                        // Continue with the next iteration.
                    }
                }
            }
            case Ast.ForEach loop -> {
                Object source = eval(loop.source(), context);
                for (Object element : Values.toList(source)) {
                    context.locals.put(loop.variable(), element);
                    try {
                        execBlock(loop.body(), context);
                    } catch (Controls.LoopBreak ignored) {
                        break;
                    } catch (Controls.LoopContinue ignored) {
                        // Continue with the next element.
                    }
                }
            }
            case Ast.BreakLoop ignored -> throw new Controls.LoopBreak();
            case Ast.ContinueLoop ignored -> throw new Controls.LoopContinue();
            case Ast.Stop ignored -> throw new Controls.ScriptStop();
            case Ast.Return returned ->
                    throw new Controls.ScriptReturn(returned.value() == null
                            ? null
                            : eval(returned.value(), context));
            case Ast.Effect effect -> {
                Object[] args = new Object[effect.arguments().size() + 1];
                args[0] = effect.name();
                for (int i = 0; i < effect.arguments().size(); i++) {
                    args[i + 1] = eval(effect.arguments().get(i), context);
                }
                Functions.dispatch(context.exec, args);
            }
            case Ast.ExpressionStmt expression -> eval(expression.expression(), context);
        }
    }

    private void assign(Ast.Assign assign, InterpreterContext context) {
        Object value;
        if (assign.operator().equals("=")) {
            value = eval(assign.value(), context);
        } else {
            Object current = readTarget(assign.target(), context);
            Object right = eval(assign.value(), context);
            value = switch (assign.operator()) {
                case "+=" -> Values.add(current, right);
                case "-=" -> Values.subtract(current, right);
                case "*=" -> Values.multiply(current, right);
                case "/=" -> Values.divide(current, right);
                default -> Values.modulo(current, right);
            };
        }
        writeTarget(assign.target(), value, context);
    }

    private Object readTarget(Ast.Target target, InterpreterContext context) {
        return switch (target) {
            case Ast.LocalTarget local -> context.locals.get(local.name());
            case Ast.GlobalTarget global -> host.variables().get(global.name());
            case Ast.PlayerTarget player -> host.variables().getPlayer(context.exec.playerId(), player.name());
            case Ast.IndexTarget index -> Values.index(eval(index.receiver(), context),
                    eval(index.key(), context));
            case Ast.PropertyTarget property -> PlayerAccess.get(eval(property.receiver(), context),
                    property.name());
        };
    }

    private void writeTarget(Ast.Target target, Object value, InterpreterContext context) {
        switch (target) {
            case Ast.LocalTarget local -> context.locals.put(local.name(), value);
            case Ast.GlobalTarget global -> host.variables().set(global.name(), value);
            case Ast.PlayerTarget player ->
                    host.variables().setPlayer(context.exec.playerId(), player.name(), value);
            case Ast.IndexTarget index -> {
                Object receiver = eval(index.receiver(), context);
                Object key = eval(index.key(), context);
                Object[] args = {"assignIndex", receiver, key, value};
                Functions.dispatch(context.exec, args);
            }
            case Ast.PropertyTarget property -> PlayerAccess.set(eval(property.receiver(), context),
                    property.name(), value);
        }
    }

    // ------------------------------------------------------------------ expressions

    private Object eval(Ast.Expr expression, InterpreterContext context) {
        return switch (expression) {
            case Ast.Literal literal -> literal.value();
            case Ast.Local local -> context.locals.get(local.name());
            case Ast.Global global -> host.variables().get(global.name());
            case Ast.PlayerVar player -> host.variables().getPlayer(context.exec.playerId(), player.name());
            case Ast.Binary binary -> binary(binary, context);
            case Ast.Unary unary -> unary(unary, context);
            case Ast.Call call -> callFunction(call, context);
            case Ast.Property property -> PlayerAccess.get(eval(property.receiver(), context),
                    property.name());
            case Ast.Index index -> Values.index(eval(index.receiver(), context),
                    eval(index.key(), context));
            case Ast.Ternary ternary -> Values.toBool(eval(ternary.test(), context))
                    ? eval(ternary.whenTrue(), context)
                    : eval(ternary.whenFalse(), context);
        };
    }

    private Object binary(Ast.Binary binary, InterpreterContext context) {
        String operator = binary.operator();
        if (operator.equals("and")) {
            return Values.toBool(eval(binary.left(), context))
                    && Values.toBool(eval(binary.right(), context));
        }
        if (operator.equals("or")) {
            return Values.toBool(eval(binary.left(), context))
                    || Values.toBool(eval(binary.right(), context));
        }
        Object left = eval(binary.left(), context);
        Object right = eval(binary.right(), context);
        return switch (operator) {
            case "+" -> Values.add(left, right);
            case "-" -> Values.subtract(left, right);
            case "*" -> Values.multiply(left, right);
            case "/" -> Values.divide(left, right);
            case "%" -> Values.modulo(left, right);
            case "==", "is" -> Values.looseEquals(left, right);
            case "!=" -> Values.notEquals(left, right);
            case "<" -> Values.less(left, right);
            case ">" -> Values.greater(left, right);
            case "<=" -> Values.lessOrEqual(left, right);
            case ">=" -> Values.greaterOrEqual(left, right);
            case "contains" -> Values.contains(left, right);
            case "<<<", ">>>" -> Values.concat(left, right);
            default -> throw new EvalException("unsupported operator '" + operator + "'");
        };
    }

    private Object unary(Ast.Unary unary, InterpreterContext context) {
        String operator = unary.operator();
        if (operator.equals("!")) {
            return !Values.toBool(eval(unary.operand(), context));
        }
        if (operator.equals("-")) {
            return -Values.toNumber(eval(unary.operand(), context));
        }
        Ast.Target target = targetOf(unary.operand());
        boolean postfix = operator.startsWith("post");
        double delta = operator.endsWith("++") ? 1.0 : -1.0;
        double current = Values.toNumber(readTarget(target, context));
        writeTarget(target, current + delta, context);
        return postfix ? current : current + delta;
    }

    private Ast.Target targetOf(Ast.Expr expression) {
        return switch (expression) {
            case Ast.Local local -> new Ast.LocalTarget(local.name(), local.pos());
            case Ast.Global global -> new Ast.GlobalTarget(global.name(), global.pos());
            case Ast.PlayerVar player -> new Ast.PlayerTarget(player.name(), player.pos());
            case Ast.Index index -> new Ast.IndexTarget(index.receiver(), index.key(), index.pos());
            case Ast.Property property ->
                    new Ast.PropertyTarget(property.receiver(), property.name(), property.pos());
            default -> throw new EvalException("expected an assignable target");
        };
    }

    private Object callFunction(Ast.Call call, InterpreterContext context) {
        Ast.FunctionDecl function = script.functions().stream()
                .filter(candidate -> candidate.name().equals(call.name()))
                .findFirst()
                .orElse(null);
        if (function != null) {
            List<Object> arguments = new ArrayList<>(call.arguments().size());
            for (Ast.Expr argument : call.arguments()) {
                arguments.add(eval(argument, context));
            }
            return call(call.name(), context, arguments.toArray());
        }
        Object[] args = new Object[call.arguments().size() + 1];
        args[0] = call.name();
        for (int i = 0; i < call.arguments().size(); i++) {
            args[i + 1] = eval(call.arguments().get(i), context);
        }
        return Functions.dispatch(context.exec, args);
    }
}
