package io.github.dsh.fastscript.core;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Conversion helpers shared by generated bytecode and the builtin library.
 *
 * <p>Script values are deliberately represented with plain JDK types — {@link Double},
 * {@link Long}, {@link String}, {@link Boolean}, {@link List}, {@link java.util.Map} — so
 * that generated code can work with primitives wherever the compiler can prove a type and
 * fall back to these helpers only when a value is dynamic.</p>
 */
public final class Values {

    private Values() {
    }

    public static final Object NULL = null;

    /** Coerces an arbitrary script value into a number. */
    public static double toNumber(Object value) {
        if (value instanceof Number number) {
            return number.doubleValue();
        }
        if (value instanceof Boolean flag) {
            return flag ? 1.0 : 0.0;
        }
        if (value instanceof String text) {
            return parseNumber(text);
        }
        throw new EvalException("cannot use " + typeName(value) + " as a number");
    }

    public static long toLong(Object value) {
        if (value instanceof Number number) {
            return number.longValue();
        }
        if (value instanceof String text) {
            return (long) parseNumber(text);
        }
        throw new EvalException("cannot use " + typeName(value) + " as a whole number");
    }

    public static int toInt(Object value) {
        return (int) toLong(value);
    }

    public static boolean toBool(Object value) {
        if (value instanceof Boolean flag) {
            return flag;
        }
        if (value instanceof Number number) {
            return number.doubleValue() != 0.0;
        }
        if (value instanceof String text) {
            return !text.isEmpty() && !text.equalsIgnoreCase("false");
        }
        return value != null;
    }

    public static String toText(Object value) {
        if (value == null) {
            return "";
        }
        if (value instanceof Double number) {
            return format(number);
        }
        if (value instanceof Number number) {
            return format(number.doubleValue());
        }
        if (value instanceof List<?> list) {
            StringBuilder builder = new StringBuilder("[");
            for (int i = 0; i < list.size(); i++) {
                if (i > 0) {
                    builder.append(", ");
                }
                builder.append(toText(list.get(i)));
            }
            return builder.append(']').toString();
        }
        return String.valueOf(value);
    }

    /** Renders an integral double without a trailing {@code .0}, matching script expectations. */
    public static String format(double value) {
        if (value == Math.floor(value) && !Double.isInfinite(value) && Math.abs(value) < 1.0e15) {
            return Long.toString((long) value);
        }
        return Double.toString(value);
    }

    private static double parseNumber(String text) {
        String trimmed = text.trim();
        if (trimmed.isEmpty()) {
            throw new EvalException("cannot use an empty text as a number");
        }
        try {
            return Double.parseDouble(trimmed);
        } catch (NumberFormatException error) {
            throw new EvalException("cannot use text '" + trimmed + "' as a number");
        }
    }

    public static String typeName(Object value) {
        if (value == null) {
            return "null";
        }
        if (value instanceof Double || value instanceof Long || value instanceof Integer) {
            return "number";
        }
        if (value instanceof String) {
            return "text";
        }
        if (value instanceof Boolean) {
            return "boolean";
        }
        if (value instanceof List) {
            return "list";
        }
        if (value instanceof java.util.Map) {
            return "map";
        }
        return value.getClass().getSimpleName();
    }

    public static boolean looseEquals(Object left, Object right) {
        if (left == null || right == null) {
            return left == right;
        }
        if (left instanceof Number a && right instanceof Number b) {
            return a.doubleValue() == b.doubleValue();
        }
        if (left instanceof String || right instanceof String) {
            return toText(left).equals(toText(right));
        }
        return Objects.equals(left, right);
    }

    /** Result of {@code >>>} / {@code <<<} style string concatenation. */
    public static String concat(Object left, Object right) {
        return toText(left) + toText(right);
    }

    public static Object add(Object left, Object right) {
        if (left instanceof String || right instanceof String) {
            return toText(left) + toText(right);
        }
        if (left instanceof Double && right instanceof Double) {
            return (double) left + (double) right;
        }
        return toNumber(left) + toNumber(right);
    }

    public static Object subtract(Object left, Object right) {
        return toNumber(left) - toNumber(right);
    }

    public static Object multiply(Object left, Object right) {
        return toNumber(left) * toNumber(right);
    }

    /** Division always yields a number; dividing by zero fails loudly instead of producing NaN. */
    public static Object divide(Object left, Object right) {
        double divisor = toNumber(right);
        if (divisor == 0.0) {
            throw new EvalException("division by zero");
        }
        return toNumber(left) / divisor;
    }

    public static Object modulo(Object left, Object right) {
        double divisor = toNumber(right);
        if (divisor == 0.0) {
            throw new EvalException("division by zero in modulo");
        }
        return toNumber(left) % divisor;
    }

    public static boolean less(Object left, Object right) {
        return compare(left, right) < 0;
    }

    public static boolean lessOrEqual(Object left, Object right) {
        return compare(left, right) <= 0;
    }

    public static boolean greater(Object left, Object right) {
        return compare(left, right) > 0;
    }

    public static boolean greaterOrEqual(Object left, Object right) {
        return compare(left, right) >= 0;
    }

    /** Numbers compare numerically, everything else compares as text. */
    private static int compare(Object left, Object right) {
        if (left instanceof Number a && right instanceof Number b) {
            return Double.compare(a.doubleValue(), b.doubleValue());
        }
        return toText(left).compareTo(toText(right));
    }

    public static boolean contains(Object container, Object element) {
        if (container == null) {
            return false;
        }
        if (container instanceof List<?> list) {
            for (Object entry : list) {
                if (looseEquals(entry, element)) {
                    return true;
                }
            }
            return false;
        }
        if (container instanceof Map<?, ?> map) {
            return map.containsKey(element) || map.containsKey(toText(element));
        }
        return toText(container).contains(toText(element));
    }

    public static boolean notEquals(Object left, Object right) {
        return !looseEquals(left, right);
    }

    public static int size(Object value) {
        if (value instanceof List<?> list) {
            return list.size();
        }
        if (value instanceof Map<?, ?> map) {
            return map.size();
        }
        if (value instanceof String text) {
            return text.length();
        }
        throw new EvalException("cannot take the size of " + typeName(value));
    }

    public static String upper(Object value) {
        return toText(value).toUpperCase(java.util.Locale.ROOT);
    }

    public static String lower(Object value) {
        return toText(value).toLowerCase(java.util.Locale.ROOT);
    }

    public static String trimmed(Object value) {
        return toText(value).trim();
    }

    public static String replace(Object source, Object target, Object replacement) {
        return toText(source).replace(toText(target), toText(replacement));
    }

    public static String substring(Object source, Object start, Object end) {
        String text = toText(source);
        int from = (int) toLong(start);
        int to = end == null ? text.length() : (int) toLong(end);
        from = Math.max(0, Math.min(from, text.length()));
        to = Math.max(from, Math.min(to, text.length()));
        return text.substring(from, to);
    }

    public static List<String> split(Object source, Object separator) {
        String text = toText(source);
        String pattern = toText(separator);
        if (pattern.isEmpty()) {
            List<String> characters = new ArrayList<>(text.length());
            for (int i = 0; i < text.length(); i++) {
                characters.add(String.valueOf(text.charAt(i)));
            }
            return characters;
        }
        return new ArrayList<>(List.of(text.split(java.util.regex.Pattern.quote(pattern), -1)));
    }

    public static String join(Object list, Object separator) {
        String glue = toText(separator);
        if (list instanceof List<?> entries) {
            StringBuilder builder = new StringBuilder();
            for (int i = 0; i < entries.size(); i++) {
                if (i > 0) {
                    builder.append(glue);
                }
                builder.append(toText(entries.get(i)));
            }
            return builder.toString();
        }
        return toText(list);
    }

    public static List<Object> toList(Object value) {
        if (value instanceof List<?> list) {
            return new ArrayList<>(list);
        }
        return new ArrayList<>();
    }

    public static Object index(Object receiver, Object key) {
        if (receiver == null) {
            return null;
        }
        if (receiver instanceof List<?> list) {
            int index = toInt(key);
            if (index < 0 || index >= list.size()) {
                return null;
            }
            return list.get(index);
        }
        if (receiver instanceof Map<?, ?> map) {
            Object value = map.get(key);
            return value != null ? value : map.get(toText(key));
        }
        if (receiver instanceof String text) {
            int index = toInt(key);
            if (index < 0 || index >= text.length()) {
                return null;
            }
            return String.valueOf(text.charAt(index));
        }
        throw new EvalException("cannot index into " + typeName(receiver));
    }
}
