package io.github.dsh.fastscript.runtime;

/**
 * Control-flow signals used by the reference interpreter.
 *
 * <p>Generated bytecode compiles loops and returns to native jumps, so it never needs these.
 * The interpreter throws them instead, which keeps statement evaluation simple. They are
 * stackless singletons, so the cost stays negligible even on hot paths.</p>
 */
public final class Controls {

    private Controls() {
    }

    /** Unwinds to the enclosing loop. */
    public static final class LoopBreak extends RuntimeException {

        private static final long serialVersionUID = 1L;

        public LoopBreak() {
            super(null, null, false, false);
        }
    }

    /** Skips to the next loop iteration. */
    public static final class LoopContinue extends RuntimeException {

        private static final long serialVersionUID = 1L;

        public LoopContinue() {
            super(null, null, false, false);
        }
    }

    /** Abandons the rest of the current handler. */
    public static final class ScriptStop extends RuntimeException {

        private static final long serialVersionUID = 1L;

        public ScriptStop() {
            super(null, null, false, false);
        }
    }

    /** Carries a function result out of nested statements. */
    public static final class ScriptReturn extends RuntimeException {

        private static final long serialVersionUID = 1L;

        private final transient Object value;

        public ScriptReturn(Object value) {
            super(null, null, false, false);
            this.value = value;
        }

        public Object value() {
            return value;
        }
    }
}
