package io.github.dsh.fastscript.runtime;

import io.github.dsh.fastscript.core.EvalException;
import io.github.dsh.fastscript.core.Values;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.bukkit.entity.Player;

/**
 * Per-invocation state handed to generated bytecode.
 *
 * <p>Generated code keeps all of its state in JVM local variable slots, including loop
 * counters, so this context only carries what the script cannot hold itself: the host bridge,
 * the triggering player and event, and the handler arguments.</p>
 */
public final class ExecContext {

    /** Event/command arguments; {@code args[0]} holds the command sender for commands. */
    private Object[] args;
    private final Host host;
    private Player player;
    private Object event;
    private final String scriptName;
    private String handlerName;
    private java.lang.invoke.MethodHandle handler;
    private boolean cancelled;
    private boolean stopped;

    public ExecContext(Host host, Player player, Object event, Object[] args,
            String scriptName, String handlerName) {
        this.host = host;
        this.player = player;
        this.event = event;
        this.args = args == null ? new Object[0] : args;
        this.scriptName = scriptName;
        this.handlerName = handlerName;
    }

    public Host host() {
        return host;
    }

    public VariableStore variables() {
        return host.variables();
    }

    public Player player() {
        return player;
    }

    public void setPlayer(Player player) {
        this.player = player;
    }

    public Object event() {
        return event;
    }

    public void setEvent(Object event) {
        this.event = event;
    }

    public Object[] args() {
        return args;
    }

    public void setArguments(Object[] args) {
        this.args = args == null ? new Object[0] : args;
    }

    public String scriptName() {
        return scriptName;
    }

    public String handlerName() {
        return handlerName;
    }

    public void setHandlerName(String handlerName) {
        this.handlerName = handlerName;
    }

    /** The compiled method currently running, invoked from the dispatcher without reflection. */
    public java.lang.invoke.MethodHandle handler() {
        return handler;
    }

    public void setHandler(java.lang.invoke.MethodHandle handler) {
        this.handler = handler;
    }

    public boolean cancelled() {
        return cancelled;
    }

    public void cancel() {
        this.cancelled = true;
        host.cancelEvent();
    }

    /** DSL name for {@link #cancel()} (kebab-case {@code cancel-event} maps here). */
    public void cancelEvent() {
        cancel();
    }

    /** Set by the {@code stop} statement to abandon the rest of a handler. */
    public void stop() {
        this.stopped = true;
    }

    public boolean stopped() {
        return stopped;
    }

    public void reset() {
        this.cancelled = false;
        this.stopped = false;
    }

    // ------------------------------------------------------------------ arguments

    public Object arg(int index) {
        return index >= 0 && index < args.length ? args[index] : null;
    }

    public String argText(int index) {
        return Values.toText(arg(index));
    }

    public double argNumber(int index) {
        return Values.toNumber(arg(index));
    }

    /** The command sender, always stored at argument index zero for command handlers. */
    public Object sender() {
        return arg(0);
    }

    public String senderName() {
        Object sender = sender();
        if (sender instanceof Player player) {
            return player.getName();
        }
        return sender == null ? "" : String.valueOf(sender);
    }

    /** Builtin {@code arg(n)}: the n-th positional command argument, one-based by convention. */
    public String argument(double index) {
        int position = (int) index;
        Object value = arg(position);
        if (value == null && position > 0) {
            value = arg(position - 1);
        }
        return Values.toText(value);
    }

    /** DSL name for {@link #argument(double)} (kebab-case maps here). */
    public String arg(double index) {
        return argument(index);
    }

    public List<Object> onlinePlayers() {
        return new ArrayList<>(org.bukkit.Bukkit.getOnlinePlayers());
    }

    // ------------------------------------------------------------------ variables

    public Object variable(String name) {
        return variables().get(name);
    }

    public void setGlobal(String name, Object value) {
        variables().set(name, value);
    }

    public Object playerVariable(String name) {
        return variables().getPlayer(playerId(), name);
    }

    public void setPlayerVariable(String name, Object value) {
        variables().setPlayer(requirePlayerId(), name, value);
    }

    // ------------------------------------------------------------------ player helpers

    public UUID playerId() {
        return player == null ? null : player.getUniqueId();
    }

    /** Resolves the UUID a player-scoped variable write should target. */
    public UUID requirePlayerId() {
        UUID id = playerId();
        if (id == null) {
            throw new EvalException("no player in context for a player-scoped variable");
        }
        return id;
    }

    // ------------------------------------------------------------------ builtin support

    public void message(String text) {
        if (player != null) {
            host.message(player, text);
        }
    }

    public void broadcast(String text) {
        host.broadcast(text);
    }

    public void log(String text) {
        host.log(text);
    }

    public void damage(double amount) {
        if (player != null) {
            host.damage(player, amount);
        }
    }

    public void heal(double amount) {
        if (player != null) {
            host.heal(player, amount);
        }
    }

    public void kill() {
        if (player != null) {
            host.kill(player);
        }
    }

    public void teleport(double x, double y, double z) {
        if (player != null) {
            host.teleport(player, x, y, z);
        }
    }

    public void give(String material, double amount) {
        if (player != null) {
            host.giveItem(player, material, Math.max(1, (int) amount));
        }
    }

    public void playSound(String sound) {
        if (player != null) {
            host.playSound(player, sound);
        }
    }

    /** DSL name for {@link #playSound(String)} (kebab-case maps here). */
    public void sound(String sound) {
        playSound(sound);
    }

    public void sendTitle(String title, String subtitle) {
        if (player != null) {
            host.sendTitle(player, title, subtitle);
        }
    }

    /** DSL name for {@link #sendTitle(String, String)} (kebab-case maps here). */
    public void title(String title, String subtitle) {
        sendTitle(title, subtitle);
    }

    public void kick(String reason) {
        if (player != null) {
            host.kick(player, reason);
        }
    }

    public void setBlock(String world, int x, int y, int z, String material) {
        host.setBlock(world, x, y, z, material);
    }

    public void runLater(Runnable task, long delayTicks) {
        host.runLater(task, delayTicks);
    }

    public List<Object> list() {
        return new ArrayList<>();
    }
}
