package io.github.dsh.fastscript.runtime;

import io.github.dsh.fastscript.core.EvalException;
import io.github.dsh.fastscript.core.Values;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import org.bukkit.entity.Player;

/**
 * Builtin operations that are not worth inlining into generated bytecode.
 *
 * <p>Everything here takes {@code Object...} arguments and returns {@code Object}: the
 * compiler packs arguments into an array and the dispatcher resolves the implementation by
 * name. Calls that matter for throughput are declared in
 * {@link io.github.dsh.fastscript.compiler.Builtins} and never reach this switch.</p>
 */
public final class Functions {

    /**
     * Every name the run-time dispatcher answers to, with the arities it accepts.
     *
     * <p>A list rather than a map: several builtins legitimately accept more than one arity,
     * for example {@code substring} with two or three arguments.</p>
     */
    private static final List<String> KNOWN = List.of(
            "player/1",
            "players/0",
            "world/1",
            "time/0",
            "set-time/1",
            "set-block/5",
            "spawn/2",
            "particle/1",
            "item/1",
            "item-amount/1",
            "material/1",
            "distance/2",
            "perm/2",
            "has-permission/2",
            "name/1",
            "uuid/1",
            "world-players/1",
            "set-health/2",
            "add-effect/3",
            "console/1",
            "list-of/1",
            "abs/1",
            "random/1",
            "size/1",
            "length/1",
            "contains/2",
            "replace/3",
            "substring/2",
            "substring/3",
            "split/2",
            "upper/1",
            "lower/1",
            "trim/1",
            "join/2",
            "floor/1",
            "ceil/1",
            "round/1",
            "min/2",
            "max/2",
            "sqrt/1",
            "pow/2",
            "list/0",
            "first/1",
            "last/1",
            "text/1",
            "number/1",
            "boolean/1");

    private Functions() {
    }

    // ------------------------------------------------------------------ inline fast paths
    //
    // The compiler inlines these as single typed calls (see Builtins), so they must exist
    // with exactly the declared descriptors. Bodies delegate to Math/Values: the same
    // semantics as the dynamic dispatcher below, without the argument array.

    /** Inclusive whole-number roll in {@code [a, b]}. */
    public static double random(double a, double b) {
        return Math.floor(a + Math.random() * (b - a + 1));
    }

    public static double min(double a, double b) {
        return Math.min(a, b);
    }

    public static double max(double a, double b) {
        return Math.max(a, b);
    }

    public static double floor(double value) {
        return Math.floor(value);
    }

    public static double ceil(double value) {
        return Math.ceil(value);
    }

    public static double round(double value) {
        return (double) Math.round(value);
    }

    public static double abs(double value) {
        return Math.abs(value);
    }

    public static double sqrt(double value) {
        return Math.sqrt(value);
    }

    public static double pow(double a, double b) {
        return Math.pow(a, b);
    }

    public static double length(Object value) {
        return (double) Values.size(value);
    }

    public static String upper(Object value) {
        return Values.upper(value);
    }

    public static String lower(Object value) {
        return Values.lower(value);
    }

    public static String join(Object left, Object right) {
        return Values.join(left, right);
    }

    /**
     * Variadic entry point used by generated code when argument types are dynamic.
     *
     * @param context the executing context, used for player-scoped defaults
     * @param args    an array whose first element is the function name
     */
    public static Object dispatch(ExecContext context, Object[] args) {
        if (args.length == 0 || !(args[0] instanceof String name)) {
            throw new EvalException("internal error: malformed builtin call");
        }
        int count = args.length - 1;
        if (name.equals("get")) {
            // Protocol shared with the compiler: ["get", receiver, key]
            return Values.index(args[1], args[2]);
        }
        if (name.equals("assignIndex")) {
            // Protocol shared with the compiler: ["assignIndex", receiver, key, value]
            assignIndex(args[1], args[2], args[3]);
            return args[1];
        }
        return switch (name) {
            case "player" -> PlayerAccess.byName(Values.toText(args[1]));
            case "players" -> PlayerAccess.onlinePlayers();
            case "world" -> PlayerAccess.world(Values.toText(args[1])).getName();
            case "time" -> context.player() == null ? 0 : context.player().getWorld().getTime();
            case "set-time" -> {
                if (context.player() != null) {
                    context.player().getWorld().setTime(Values.toLong(args[1]));
                }
                yield null;
            }
            case "set-block" -> {
                context.setBlock(Values.toText(args[1]), (int) Values.toLong(args[2]),
                        (int) Values.toLong(args[3]), (int) Values.toLong(args[4]), Values.toText(args[5]));
                yield null;
            }
            case "spawn" -> {
                if (context.player() != null) {
                    context.player().getWorld().spawnEntity(context.player().getLocation(),
                            org.bukkit.entity.EntityType.valueOf(
                                    Values.toText(args[1]).toUpperCase(Locale.ROOT)));
                }
                yield null;
            }
            case "particle" -> {
                if (context.player() != null) {
                    context.player().getWorld().spawnParticle(
                            org.bukkit.Particle.valueOf(Values.toText(args[1]).toUpperCase(Locale.ROOT)),
                            context.player().getLocation(), 1);
                }
                yield null;
            }
            case "item" -> PlayerAccess.material(Values.toText(args[1])).name();
            case "material" -> PlayerAccess.material(Values.toText(args[1])).name();
            case "item-amount" -> {
                Player player = requirePlayer(context, args[1]);
                yield (double) player.getItemInHand().getAmount();
            }
            case "distance" -> {
                Player player = requirePlayer(context, args[1]);
                Player other = requirePlayer(context, args[2]);
                yield player.getLocation().distance(other.getLocation());
            }
            case "perm", "has-permission" -> requirePlayer(context, args[1]).hasPermission(Values.toText(args[2]));
            case "name" -> requireObjectPlayer(context, args[1]).getName();
            case "uuid" -> requireObjectPlayer(context, args[1]).getUniqueId().toString();
            case "world-players" -> context.host().scriptInfo().getOrDefault("world-players-" + args[1], List.of());
            case "set-health" -> {
                Player player = requirePlayer(context, args[1]);
                player.setHealth(clamp(Values.toNumber(args[2]), 0.0, player.getMaxHealth()));
                yield null;
            }
            case "add-effect" -> {
                Player player = requirePlayer(context, args[1]);
                org.bukkit.potion.PotionEffectType type =
                        org.bukkit.potion.PotionEffectType.getByName(Values.toText(args[2]).toUpperCase(Locale.ROOT));
                if (type == null) {
                    throw new EvalException("unknown potion effect '" + args[2] + "'");
                }
                player.addPotionEffect(new org.bukkit.potion.PotionEffect(type,
                        (int) (Values.toNumber(args[3]) * 20), 0));
                yield null;
            }
            case "console" -> {
                context.host().log(Values.toText(args[1]));
                yield null;
            }
            case "list-of" -> new ArrayList<>(Arrays.asList(args).subList(1, args.length));
            case "list" -> new ArrayList<>();
            case "first" -> {
                List<Object> items = Values.toList(args[1]);
                yield items.isEmpty() ? null : items.get(0);
            }
            case "last" -> {
                List<Object> items = Values.toList(args[1]);
                yield items.isEmpty() ? null : items.get(items.size() - 1);
            }
            case "size", "length" -> (double) Values.size(args[1]);
            case "contains" -> Values.contains(args[1], args[2]);
            case "replace" -> Values.replace(args[1], args[2], args[3]);
            case "substring" -> count == 3
                    ? Values.substring(args[1], args[2], args[3])
                    : Values.substring(args[1], args[2], null);
            case "split" -> Values.split(args[1], args[2]);
            case "upper" -> Values.upper(args[1]);
            case "lower" -> Values.lower(args[1]);
            case "trim" -> Values.trimmed(args[1]);
            case "join" -> Values.join(args[1], args[2]);
            case "floor" -> Math.floor(Values.toNumber(args[1]));
            case "ceil" -> Math.ceil(Values.toNumber(args[1]));
            case "round" -> (double) Math.round(Values.toNumber(args[1]));
            case "abs" -> Math.abs(Values.toNumber(args[1]));
            case "sqrt" -> Math.sqrt(Values.toNumber(args[1]));
            case "pow" -> Math.pow(Values.toNumber(args[1]), Values.toNumber(args[2]));
            case "min" -> Math.min(Values.toNumber(args[1]), Values.toNumber(args[2]));
            case "max" -> Math.max(Values.toNumber(args[1]), Values.toNumber(args[2]));
            case "number" -> Values.toNumber(args[1]);
            case "text" -> Values.toText(args[1]);
            case "boolean" -> Values.toBool(args[1]);
            default -> throw new EvalException("unknown function '" + name + "' with " + count + " argument(s)");
        };
    }

    private static Player requirePlayer(ExecContext context, Object value) {
        if (value == null || (value instanceof String text && text.equalsIgnoreCase("self"))) {
            if (context.player() == null) {
                throw new EvalException("no player in context");
            }
            return context.player();
        }
        if (value instanceof Player player) {
            return player;
        }
        if (value instanceof String text) {
            Player resolved = PlayerAccess.byName(text);
            if (resolved == null) {
                throw new EvalException("player '" + text + "' is not online");
            }
            return resolved;
        }
        throw new EvalException("expected a player name, got " + Values.typeName(value));
    }

    private static Player requireObjectPlayer(ExecContext context, Object value) {
        return requirePlayer(context, value);
    }

    private static double clamp(double value, double min, double max) {
        return Math.max(min, Math.min(max, value));
    }

    /** Writes into a list or map in place; returns nothing because containers are mutable. */
    private static void assignIndex(Object receiver, Object key, Object value) {
        if (receiver instanceof List) {
            @SuppressWarnings("unchecked")
            List<Object> list = (List<Object>) receiver;
            int index = Values.toInt(key);
            if (index < 0 || index >= list.size()) {
                throw new EvalException("index " + index + " is out of bounds for a list of size "
                        + list.size());
            }
            list.set(index, value);
            return;
        }
        if (receiver instanceof Map) {
            @SuppressWarnings("unchecked")
            Map<Object, Object> map = (Map<Object, Object>) receiver;
            map.put(Values.toText(key), value);
            return;
        }
        throw new EvalException("cannot assign into " + Values.typeName(receiver));
    }

    /** Called once during plugin start-up so the compiler knows which names exist. */
    public static void registerCompilerEntries() {
        io.github.dsh.fastscript.compiler.Builtins.registerDynamic(KNOWN);
    }

    /** Kept for diagnostics such as {@code /fs functions}. */
    public static List<String> documentedNames() {
        List<String> names = new ArrayList<>(KNOWN);
        names.sort(String::compareTo);
        return names;
    }
}
