package io.github.dsh.fastscript.runtime;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Base class of every compiled script.
 *
 * <p>The generated subclass builds an instance of itself in a static {@code create} factory and
 * registers its handlers through the {@code add*} methods below. Keeping registration in
 * generated bytecode means loading a script performs no annotation scanning or classpath
 * search: the loader simply calls one static method.</p>
 */
public abstract class ScriptHandle {

    private final String id;
    private final String sourceName;
    private final Map<String, TriggerSpec> triggers = new LinkedHashMap<>();
    private final Map<String, CommandSpec> commands = new LinkedHashMap<>();
    private final Map<String, FunctionSpec> functions = new LinkedHashMap<>();
    private final List<String> declaredGlobals = new ArrayList<>();
    private Class<?> compiledClass;
    private volatile boolean enabled = true;

    protected ScriptHandle(String id, String sourceName) {
        this.id = id;
        this.sourceName = sourceName;
    }

    public String id() {
        return id;
    }

    public String sourceName() {
        return sourceName;
    }

    public Class<?> compiledClass() {
        return compiledClass;
    }

    public void bindClass(Class<?> compiledClass) {
        this.compiledClass = compiledClass;
    }

    public boolean enabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    // ------------------------------------------------------------------ registration

    public void addTrigger(TriggerSpec spec) {
        triggers.put(spec.eventName(), spec);
    }

    public void addCommand(CommandSpec spec) {
        commands.put(spec.name().toLowerCase(java.util.Locale.ROOT), spec);
    }

    public void addFunction(FunctionSpec spec) {
        functions.put(spec.name(), spec);
    }

    public List<String> declaredGlobals() {
        return declaredGlobals;
    }

    public void declareGlobal(String name) {
        declaredGlobals.add(name);
    }

    // ------------------------------------------------------------------ accessors

    public Map<String, TriggerSpec> triggers() {
        return Map.copyOf(triggers);
    }

    public Map<String, CommandSpec> commands() {
        return Map.copyOf(commands);
    }

    public Map<String, FunctionSpec> functions() {
        return Map.copyOf(functions);
    }

    public Optional<TriggerSpec> trigger(String eventName) {
        return Optional.ofNullable(triggers.get(eventName));
    }

    public Optional<CommandSpec> command(String name) {
        return Optional.ofNullable(commands.get(name.toLowerCase(java.util.Locale.ROOT)));
    }

    @Override
    public String toString() {
        return "ScriptHandle[" + id + " triggers=" + triggers.size() + " commands=" + commands.size()
                + " functions=" + functions.size() + "]";
    }
}
